# Generated by Django 5.0.6 on 2024-10-09 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0002_alter_ordendecompra_usuario_direccionenvio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendecompra',
            name='direccion_envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='sitio.direccionenvio'),
        ),
    ]
