# Generated by Django 5.0.6 on 2024-10-09 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0003_alter_ordendecompra_direccion_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleorden',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='sitio.ordendecompra'),
        ),
        migrations.AlterField(
            model_name='detalleorden',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitio.producto'),
        ),
    ]
