# Generated by Django 5.0.6 on 2024-10-09 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0004_alter_detalleorden_orden_alter_detalleorden_producto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Metadata',
        ),
    ]
