# Generated by Django 5.1.2 on 2024-11-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0005_delete_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id_metadata', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255, null=True)),
                ('keyword', models.TextField()),
                ('correo', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='direccionenvio',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='direccionenvio',
            name='codigo_postal',
        ),
        migrations.AlterField(
            model_name='direccionenvio',
            name='region',
            field=models.CharField(choices=[('Metropolitana', 'Región Metropolitana')], max_length=50),
        ),
    ]
