# Generated by Django 5.1.3 on 2024-12-03 02:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0006_metadata_remove_direccionenvio_ciudad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleorden',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
